---
output:
  html_document:
    highlight: null
    css: style.css
    self_contained: no
    keep_md: true
---

```{r, echo=FALSE, warning=FALSE, message=FALSE}
library(stringr)

date <- "2/06/2020"

quarter <- "Winter2020"
date <- "02/06"
week_folder <- "02-06_Becker"


vendor <- "TBD"
title <- "School, Studying, and Smarts: The Gender of Education Across 80 Years of American Print Media, 1930-2009"


speaker <- "Andrei Boutyline"
department <- "Assistant Professor, Department of Sociology"
university <- "University of Michigan"
github_home <- "https://github.com/uchicago-computation-workshop"

#Update Weekly
issues_url <- "https://github.com/uchicago-computation-workshop/Winter2020/issues/5"


#Papers

week_paper_ref0 <- 'Boutyline, Andrei, Alina Arseniev-Koehler, and Devin J. Cornell. 2020. "School, Studying, and Smarts: The Gender of Education Across 80 Years of American Print Media, 1930-2009," Working Paper, January 29, 2020.'
week_paper_file0 <- "Boutyline_Arseniev-Koehler_and_Cornell.pdf"
week_paper_file0 <- ""


#No Need to Edit
week_repo <- paste0("https://github.com/uchicago-computation-workshop/",quarter,"/tree/master/",week_folder)

readings0 <- paste0("[", week_paper_ref0,"](https://github.com/uchicago-computation-workshop/",quarter,"/blob/master/", week_folder,"/",week_paper_file0,")")


```



<br>

<h3 class=pfblock-header> The Computational Social Science Workshop Presents </h3>

<h1 class=pfblock-header3> `r speaker` </h1>
<h3 class=pfblock-header3> `r department` </h3>
<h3 class=pfblock-header3> `r university` </h3>

<br><br>



<p class=pfblock-header3>The <a href="https://macss.uchicago.edu/content/computation-workshop"> Computational Social Science Workshop </a> at the University of Chicago cordially invites you to attend this week's talk:</p>



<br>

<div class=pfblock-header3>
<h2 class=pfblock-header>
  <a href=`r week_repo`> `r title` </a>
</h2>

<br>
</div>



<p class=footertext2>

**Summary:** In recent decades women’s educational attainment has increasingly come to surpass men’s. While recent work made strides in incorporating cultural models of gender into accounts of this reversal, it has implicitly assumed that these models have themselves remained substantively constant. In this article, we apply neural network word embeddings to a 200-million-word corpus of American print media (1930-2009) to examine whether and how these cultural models have changed. Our approach lets us estimate the extent to which each of over 10,000 English words occurs in feminine versus masculine contexts at different time points. We use this to track the changing gendered connotations of terms related to school, studying, socio-behavioral skills, behavioral problems, intelligence, and unintelligence. Our results point to three ideal-typical trajectories: (1) socio-behavioral skills and behavioral problems start out significantly feminine and masculine, respectively, and retain those connotations throughout the entire time period; (2) school and studying start out without significant gendered connotations, but finish with significant feminine connotations; (3) intelligence and unintelligence start out neutral or slightly feminine but finish significantly masculine. There is an exceptionally strong negative correlation between trends (2) and (3), which leads us to speculate that both changes are part of one overarching cultural shift.


</p>

<br>

<h4 class=pfblock-header3> Thursday, `r date` </h4>
<h4 class=pfblock-header3> 11:00am-12:20pm </h4>
<h4 class=pfblock-header3> Cummings Life Science Center, Room 101 </h4>

<!-- <br> -->

<!-- <p class=pfblock-header3>A light lunch will be provided by `r vendor`.</p> -->

<br><br>

<p class=footertext2>

**`r speaker`**'s research focuses on culture, cognition, methodology, and public opinion. He examines the supra-individual aspects of attitudes, tastes, and cognitive representations, with a special focus on political views. He is broadly interested in the society-wide distribution of these cultural elements, and the social and cognitive processes that give rise to this distribution. He draws on network analysis, statistics, and computer science to develop novel methods for these investigations. In a separate research stream, he studies the effects of political disagreement on social network structure. His work has appeared in the *American Journal of Sociology*, *Sociological Science*, and *Political Psychology*.
</p>


<br>

This week's suggested readings:

- `r readings0`
- **Note**: This reading was privately sent to MACSS students and faculty. Please do not share or distribute the file.

<br><br>

---

<p class=footertext> The 2019-2020 <a href="https://macss.uchicago.edu/content/computation-workshop"> Computational Social Science Workshop </a> meets each Thursday from 11 a.m. to 12:20 p.m. in the Cummings Life Science Center, Room 101. All interested faculty and graduate students are welcome.</p>




<p class=footertext>Students in the Masters of Computational Social Science program are expected to attend and join the discussion by posting a comment on the <a href=`r issues_url`>issues page</a> of the <a href=`r week_repo`>workshop's public repository on GitHub.</a></p>
