---
output:
  html_document:
    highlight: null
    css: style.css
    self_contained: no
    keep_md: true
---

```{r, echo=FALSE, warning=FALSE, message=FALSE}
library(stringr)

date <- "1/9/2020"

quarter <- "Winter2020"
date <- "01/09"
week_folder <- "01-09_Boudourides"


vendor <- "TBD"
title <- "Network Science or Applied Graph Theory? Examining the Network of Indirect Collaboration in a Department of Mathematics"


speaker <- "Moses Boudourides"
department <- "Visiting Professor of Mathematics - New York University Abu Dhabi"
university <- "Faculty - Northwestern University School of Professional Studies Data Science Program"
github_home <- "https://github.com/uchicago-computation-workshop"

#Update Weekly
issues_url <- "https://github.com/uchicago-computation-workshop/Winter2020/issues/1"


#Papers

week_paper_ref0 <- 'Boudourides and Lenis. "Boundary Stimulation of Social Influence Networks."'
week_paper_file0 <- "Boudourides_Lenis_BoundaryStimulation.pdf"


week_paper_ref1 <- 'Boudourides and Lenis (2016). "Dominating Sets and Ego-Centered Decompositions in Social Networks." *EPJST* 225:1293-1310.'
week_paper_file1 <- "Boudourides_Lenis_EPJST.pdf"


#No Need to Edit
week_repo <- paste0("https://github.com/uchicago-computation-workshop/",quarter,"/tree/master/",week_folder)

readings0 <- paste0("[", week_paper_ref0,"](https://github.com/uchicago-computation-workshop/",quarter,"/blob/master/", week_folder,"/",week_paper_file0,")")
readings1 <- paste0("[", week_paper_ref1,"](https://github.com/uchicago-computation-workshop/",quarter,"/blob/master/", week_folder,"/",week_paper_file1,")")


```



<br>

<h3 class=pfblock-header> The Computational Social Science Workshop Presents </h3>

<h1 class=pfblock-header3> `r speaker` </h1>
<h3 class=pfblock-header3> `r department` </h3>
<h3 class=pfblock-header3> `r university` </h3>

<br><br>



<p class=pfblock-header3>The <a href="https://macss.uchicago.edu/content/computation-workshop"> Computational Social Science Workshop </a> at the University of Chicago cordially invites you to attend this week's talk:</p>



<br>

<div class=pfblock-header3>
<h2 class=pfblock-header>
  <a href=`r week_repo`> `r title` </a>
</h2>

<br>
</div>



<p class=footertext2>

**Summary:** During the last ten years, network science has emerged as a strongly
interdisciplinary new field of studies in academia. Here, I will trace
the epistemic development of the field examining the mathematical
origins of certain important concepts of network analysis as they were
exported mainly from the rudiments of graph theory. I will discuss a
few examples of schools of mathematics (mostly in USA) starting to
offer courses and to host research on network science. Moreover, I
will present the Wikipedia network stemming from the 3 Wikipedia pages
(Graph theory, Network science, Complex network) and I will discuss
the structure of this Wikipedia network based on the graph-theoretic
notion of minimum dominating sets. The exemplary network that will be
presented here is that of the (direct and) indirect collaborations
among members of the NYUAD Faculty of Mathematics generated by data
extracted from the MathSciNet database of the American Mathematical
Society. Furthermore, I will analyze the bipartite graph of faculty
members and research interests using the tools of Formal Concept
Analysis. Finally, I will model the effect of a network influence
process on the Math collaboration network when research areas are
sources of boundary influence simulations.


</p>

<br>

<h4 class=pfblock-header3> Thursday, `r date` </h4>
<h4 class=pfblock-header3> 11:00am-12:20pm </h4>
<h4 class=pfblock-header3> Cummings Life Science Center, Room 101 </h4>

<!-- <br> -->

<!-- <p class=pfblock-header3>A light lunch will be provided by `r vendor`.</p> -->

<br><br>

<p class=footertext2>

**`r speaker`** is in the Faculty of Northwestern University School of Professional Studies Data Science Program. Currently he is Visiting Professor of Mathematics at the New York University Abu Dhabi (NYUAD), where he is affiliated to the Research Group in Network Science [RGNS](https://sites.google.com/nyu.edu/rgns/home).
</p>


<br>

This week's suggested readings:

- `r readings0`
- `r readings1`

<br>

<br><br>

---

<p class=footertext> The 2019-2020 <a href="https://macss.uchicago.edu/content/computation-workshop"> Computational Social Science Workshop </a> meets each Thursday from 11 a.m. to 12:20 p.m. in the Cummings Life Science Center, Room 101. All interested faculty and graduate students are welcome.</p>




<p class=footertext>Students in the Masters of Computational Social Science program are expected to attend and join the discussion by posting a comment on the <a href=`r issues_url`>issues page</a> of the <a href=`r week_repo`>workshop's public repository on GitHub.</a></p>
