---
output:
  html_document:
    highlight: null
    css: style.css
    self_contained: no
    keep_md: true
---

```{r, echo=FALSE, warning=FALSE, message=FALSE}
library(stringr)

date <- "3/6/2020"

quarter <- "Winter2020"
date <- "03/06"
week_folder <- "03-06_Youn"


vendor <- "Northern Taste"
title <- "How exploitation and exploration shape the knowledge space"


speaker <- "Hyejin Youn"
department <- "Assistant Professor of Management & Organizations"
university <- "Northwestern University - Kellogg School of Management"
github_home <- "https://github.com/uchicago-computation-workshop"

#Update Weekly
issues_url <- "https://github.com/uchicago-computation-workshop/Winter2020/issues/7"


#Papers

week_paper_ref0 <- 'Van Der Wouden, Frank and Hyejin Youn. 2020. "Impact of geographical distance on acquiring know-how through scientific collaboration." Working Paper.'
week_paper_file0 <- "youn_know-how.pdf"


week_paper_ref1 <- ''
week_paper_file1 <- ""


#No Need to Edit
week_repo <- paste0("https://github.com/uchicago-computation-workshop/",quarter,"/tree/master/",week_folder)

readings0 <- paste0("[", week_paper_ref0,"](https://github.com/uchicago-computation-workshop/",quarter,"/blob/master/", week_folder,"/",week_paper_file0,")")
readings1 <- paste0("[", week_paper_ref1,"](https://github.com/uchicago-computation-workshop/",quarter,"/blob/master/", week_folder,"/",week_paper_file1,")")


```



<br>

<h3 class=pfblock-header> The Computational Social Science Workshop Presents </h3>

<h1 class=pfblock-header3> `r speaker` </h1>
<h3 class=pfblock-header3> `r department` </h3>
<h3 class=pfblock-header3> `r university` </h3>

<br><br>



<p class=pfblock-header3>The <a href="https://macss.uchicago.edu/content/computation-workshop"> Computational Social Science Workshop </a> at the University of Chicago cordially invites you to attend this week's talk:</p>



<br>

<div class=pfblock-header3>
<h2 class=pfblock-header>
  <a href=`r week_repo`> `r title` </a>
</h2>

<br>
</div>



<p class=footertext2>

**Summary:** Innovations have been achieved by combining existing knowledge with novel additions. The combinatorial nature of innovation is mainly governed by exploitation and exploration, behaviors that reuse known combinations and discover new possibilities. The trade-off between them, a well-known dilemma that innovators face, is not only affected by, but also change knowledge space where innovations occur. To investigate how the trade-off contributes to knowledge space, we present a network model that sub-linearly grows by following Heaps' law and creates links with adjacent possibles, and compare model networks to empirical knowledge spaces constructed from patents and research papers. With the balanced trade-off, the model reproduces structural properties found across empirical knowledge spaces, including broad strength distribution, significant local clustering, and especially modular structure that is often considered taken for granted. If either exploitation or exploration dominates the trade-off, these structures could not be obtained. Interestingly, the empirical spaces appear to evolve with the balanced trade-off, suggesting collective behaviors that balance exploitation and exploration naturally shape knowledge modules. Our network model not only explains why modular structure exists within knowledge spaces but also provides insights into the co-evolution of microscopic behaviors and modular structure.


</p>

<br>

<h4 class=pfblock-header3> Friday, `r date` </h4>
<h4 class=pfblock-header3> 11:00am-12:20pm </h4>
<h4 class=pfblock-header3> 1155 E 60TH ST, Room 289A </h4>

<!-- <br> -->

<p class=pfblock-header3>A light reception will be provided by `r vendor` following the talk. The reception will be held in the new MACSS lounge, 1155 E 60TH ST, Room 224.</p>

<br><br>

<p class=footertext2>

**`r speaker`** is an Assistant Professor of Management & Organization Department at the Kellogg School of Management, and a core faculty at NICO, the Northwestern Institute on Complex Systems. She is also Royal Society of Arts fellow, and an external fellow at London Mathematical Laboratory, London, UK. Prior to joining Kellogg, she worked at University of Oxford, Harvard University, and MIT Media Lab, and Santa Fe Institute, as a research fellow. Hyejin received her PhD in Physics in 2011 from Korea Advanced Institute of Science and Technology (KAIST). She was a Principal Investigator of the project a National Science Foundation grant (USA) to study Technological Change from the Map of Capabilities. 

Her research interests are to understand the interplay between technological innovation and socio-economic systems (urbanisation, economic diversity and specialisation, invention activity, future of work). Her highly interdisciplinary approach often results in broad collaborations ranging from mathematicians, computer scientists, economists, sociologists, anthropologists, to archeologists. Her work has been published in general audience such as Nature communication, and PNAS, as well as top specialized journals such Physics Review Letter, and Evolutionary Anthropology, and has been featured in The Econonmist, Forbes, The Guardian, WIRED, Scientific America, MIT Technonlogy Review, among other major global media outlets. Her goal is to develop a theoretical, yet empirically grounded, framework that will enable us to turn the increasing volumes of data into scientific insights and well-designed policies, an approach known as computational social science. The mathematical tools and computational methods that are used include scaling theory, spatial analysis (including percolation theory, information theory and fractal dimension analysis), statistics, and network theory. 
</p>


<br>

This week's suggested readings:

- `r readings0`

<br>

<br><br>

---

<p class=footertext> The 2019-2020 <a href="https://macss.uchicago.edu/content/computation-workshop"> Computational Social Science Workshop </a> meets each Thursday from 11 a.m. to 12:20 p.m. in the Cummings Life Science Center, Room 101. All interested faculty and graduate students are welcome.</p>




<p class=footertext>Students in the Masters of Computational Social Science program are expected to attend and join the discussion by posting a comment on the <a href=`r issues_url`>issues page</a> of the <a href=`r week_repo`>workshop's public repository on GitHub.</a></p>
