---
output:
  html_document:
    highlight: null
    css: style.css
    self_contained: no
    keep_md: true
---

```{r, echo=FALSE, warning=FALSE, message=FALSE}
library(stringr)

date <- "2/27/2020"

quarter <- "Winter2020"
date <- "02/27"
week_folder <- "02-27_Ferrari"


vendor <- "Papa Johns"
title <- "Modeling Context-Dependent Latent Effect Heterogeneity with Applications to Study Public Political Polarization"


speaker <- "Diogo Ferrari"
department <- "Assistant Instructional Professor in Computational Social Science"
university <- "University of Chicago"
github_home <- "https://github.com/uchicago-computation-workshop"

#Update Weekly
issues_url <- "https://github.com/uchicago-computation-workshop/Winter2020/issues/6"


#Papers

week_paper_ref0 <- 'Ferrari, Diogo. 2019. "Modeling Context-Dependent Latent Effect Heterogeneity." *Political Analysis* 28(1):20-46.'
week_paper_file0 <- "ferrari2020modeling.pdf"


week_paper_ref1 <- ''
week_paper_file1 <- ""


#No Need to Edit
week_repo <- paste0("https://github.com/uchicago-computation-workshop/",quarter,"/tree/master/",week_folder)

readings0 <- paste0("[", week_paper_ref0,"](https://github.com/uchicago-computation-workshop/",quarter,"/blob/master/", week_folder,"/",week_paper_file0,")")
readings1 <- paste0("[", week_paper_ref1,"](https://github.com/uchicago-computation-workshop/",quarter,"/blob/master/", week_folder,"/",week_paper_file1,")")


```



<br>

<h3 class=pfblock-header> The Computational Social Science Workshop Presents </h3>

<h1 class=pfblock-header3> `r speaker` </h1>
<h3 class=pfblock-header3> `r department` </h3>
<h3 class=pfblock-header3> `r university` </h3>

<br><br>



<p class=pfblock-header3>The <a href="https://macss.uchicago.edu/content/computation-workshop"> Computational Social Science Workshop </a> at the University of Chicago cordially invites you to attend this week's talk:</p>



<br>

<div class=pfblock-header3>
<h2 class=pfblock-header>
  <a href=`r week_repo`> `r title` </a>
</h2>

<br>
</div>



<p class=footertext2>

**Summary:** In this workshop, I will introduce a hierarchical Dirichlet process of generalized linear models in which the latent heterogeneity in the effect of individual-level covariates depends on context-level features. Such a model is important in political analyses, for instance, when the data comes from different countries and the latent heterogeneity in political behavior can be a function of country-level characteristics. The supporting paper proposes a semi-parametric Bayesian approach, a Gibbs sampler for the general model, a special Gibbs sampler for Gaussian outcome variables, and a Hamiltonian Monte Carlo within Gibbs to handle discrete outcome variables. I demonstrate the importance of accounting for latent heterogeneity with a Monte Carlo exercise and with two applications that replicate recent scholarly work. I demonstrate how the proposed allow us to identify latent structures in public political polarization.


</p>

<br>

<h4 class=pfblock-header3> Thursday, `r date` </h4>
<h4 class=pfblock-header3> 11:00am-12:20pm </h4>
<h4 class=pfblock-header3> Cummings Life Science Center, Room 101 </h4>

<!-- <br> -->

<!-- <p class=pfblock-header3>A light lunch will be provided by `r vendor`.</p> -->

<br><br>

<p class=footertext2>

**`r speaker`** is an Assistant Instructional Professor in the Masters in Computational Social Science program and a Political Scientist with expertise in OECD and Latin America countries. He holds a PhD degree in Political Science and Scientific Computing from the University of Michigan, Ann Arbor, and an MA degree in Statistics from the same university. Dr. Ferrari is interested in a wide range of topics in computational social sciences, comparative politics, and political methodology. He teaches courses on Computational Methods for Political Science, Advanced Machine Learning, Bayesian Statistics, and Introduction to Computer Science. His doctoral research proposes innovative hierarchical unsupervised learning methods to estimate latent interactions in observational and experimental studies and to measure the polarization of policy preferences. Broadly, his substantive research combines political economy, political sociology, and social cognition approaches to study the formation of political preferences. In his recent research, he examines the connections between people's socioeconomic conditions, cognitive perceptions about the socioeconomic environment, and political opinions. 
</p>


<br>

This week's suggested readings:

- `r readings0`

<br>

<br><br>

---

<p class=footertext> The 2019-2020 <a href="https://macss.uchicago.edu/content/computation-workshop"> Computational Social Science Workshop </a> meets each Thursday from 11 a.m. to 12:20 p.m. in the Cummings Life Science Center, Room 101. All interested faculty and graduate students are welcome.</p>




<p class=footertext>Students in the Masters of Computational Social Science program are expected to attend and join the discussion by posting a comment on the <a href=`r issues_url`>issues page</a> of the <a href=`r week_repo`>workshop's public repository on GitHub.</a></p>
