---
output:
  html_document:
    highlight: null
    css: style.css
    self_contained: no
    keep_md: true
---

```{r, echo=FALSE, warning=FALSE, message=FALSE}
library(stringr)

date <- "1/23/2020"

quarter <- "Winter2020"
date <- "01/23"
week_folder <- "01-23_Wang"


vendor <- "Papa Johns"
title <- "Toward a Science of Failure"


speaker <- "Dashun Wang"
department <- "Associate Professor of Management and Organizations - Kellogg School of Management"
university <- "Northwestern University"
github_home <- "https://github.com/uchicago-computation-workshop"

#Update Weekly
issues_url <- "https://github.com/uchicago-computation-workshop/Winter2020/issues/3"


#Papers

week_paper_ref0 <- 'Wang, Yang, Benjamin F. Jones, and Dashun Wang. 2019. "Early-career setback and future career impact." *Nature Communications* 10:4331. DOI:10.1038/s41467-019-12189-3.'
week_paper_file0 <- "s41467-019-12189-3.pdf"


week_paper_ref1 <- 'Yin, Yian, Yang Wang, James A. Evans, and Dashun Wang. 2019. "Quantifying the dynamics of failure across science, startups and security." *Nature* 575:190–194.'
week_paper_file1 <- "s41586-019-1725-y.pdf"


#No Need to Edit
week_repo <- paste0("https://github.com/uchicago-computation-workshop/",quarter,"/tree/master/",week_folder)

readings0 <- paste0("[", week_paper_ref0,"](https://github.com/uchicago-computation-workshop/",quarter,"/blob/master/", week_folder,"/",week_paper_file0,")")
readings1 <- paste0("[", week_paper_ref1,"](https://github.com/uchicago-computation-workshop/",quarter,"/blob/master/", week_folder,"/",week_paper_file1,")")


```



<br>

<h3 class=pfblock-header> The Computational Social Science Workshop Presents </h3>

<h1 class=pfblock-header3> `r speaker` </h1>
<h3 class=pfblock-header3> `r department` </h3>
<h3 class=pfblock-header3> `r university` </h3>

<br><br>



<p class=pfblock-header3>The <a href="https://macss.uchicago.edu/content/computation-workshop"> Computational Social Science Workshop </a> at the University of Chicago cordially invites you to attend this week's talk:</p>



<br>

<div class=pfblock-header3>
<h2 class=pfblock-header>
  <a href=`r week_repo`> `r title` </a>
</h2>

<br>
</div>



<p class=footertext2>

**Summary:** Setbacks are an integral part of a scientific career, yet little is known about their long-term effects. Here we examine junior scientists applying for National Institutes of Health R01 grants. By focusing on proposals that fell just below and just above the funding threshold, we compare near-miss with narrow-win applicants, and find that an early-career setback has powerful, opposing effects. On the one hand, it significantly increases attrition, predicting more than a 10% chance of disappearing permanently from the NIH system. Yet, despite an early setback, individuals with near misses systematically outperform those with narrow wins in the longer run. Moreover, this performance advantage seems to go beyond a screening mechanism, suggesting early-career setback appears to cause a performance improvement among those who persevere. Overall, these findings are consistent with the concept that “what doesn’t kill me makes me stronger,” which may have broad implications for identifying, training and nurturing junior scientists. I also discuss a second project in which we model how human achievements are often preceded by repeated failures to illuminate the mechanisms that govern the dynamics of failure. Building on previous research relating to innovation, human dynamics and learning, we develop a simple one-parameter model that mimics how successful future attempts build on past efforts. Solving this model analytically suggests that a phase transition separates the dynamics of failure into regions of progression or stagnation and predicts that, near the critical threshold, agents who share similar characteristics and learning strategies may experience fundamentally different outcomes following failures. Above the critical point, agents exploit incremental refinements to systematically advance towards success, whereas below it, they explore disjoint opportunities without a pattern of improvement. The model makes several empirically testable predictions, demonstrating that those who eventually succeed and those who do not may initially appear similar, but can be characterized by fundamentally distinct failure dynamics in terms of the efficiency and quality associated with each subsequent attempt. We validated these with large-scale data from three disparate domains—scientists attempting to obtain National Institutes of Health (NIH) grants to fund their research, entrepreneurs seeking to successfully exit their startup ventures, and terrorist organizations trying claim casualties in violent attacks. Our findings unveil detectable yet previously unknown early signals that enable us to identify failure dynamics that predict ultimate success or failure. Given the ubiquitous nature of failure and the paucity of quantitative approaches to understand it, these results represent an initial step towards deeper understanding of the complex dynamics underlying failure.


</p>

<br>

<h4 class=pfblock-header3> Thursday, `r date` </h4>
<h4 class=pfblock-header3> 11:00am-12:20pm </h4>
<h4 class=pfblock-header3> Cummings Life Science Center, Room 101 </h4>

<!-- <br> -->

<p class=pfblock-header3>A light lunch will be provided by `r vendor`.</p>

<br><br>

<p class=footertext2>

**`r speaker`** is an Associate Professor of Management and Organizations at the Kellogg School of Management, and (by courtesy) the McCormick School of Engineering, at Northwestern University. At Kellogg, he is the Founding Director of the Center for Science of Science and Innovation (CSSI). He is also a core faculty at the Northwestern Institute on Complex Systems (NICO). His current research focus is on Science of Science, a quest to turn the scientific methods and curiosities upon ourselves, hoping to use and develop tools from complexity sciences and artificial intelligence to broadly explore the opportunities for innovation and promises of prosperity offered by the recent data explosion in science. Dashun is a recipient of the AFOSR Young Investigator award (2016) and Poets & Quants Best 40 Under 40 Professors (2019).
</p>


<br>

This week's suggested readings:

- `r readings0`
- `r readings1`

<br>

<br><br>

---

<p class=footertext> The 2019-2020 <a href="https://macss.uchicago.edu/content/computation-workshop"> Computational Social Science Workshop </a> meets each Thursday from 11 a.m. to 12:20 p.m. in the Cummings Life Science Center, Room 101. All interested faculty and graduate students are welcome.</p>




<p class=footertext>Students in the Masters of Computational Social Science program are expected to attend and join the discussion by posting a comment on the <a href=`r issues_url`>issues page</a> of the <a href=`r week_repo`>workshop's public repository on GitHub.</a></p>
